name: CI/CD for Express.js on VPS

on:
  push:
    branches:
      - main  # Trigger when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy code to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /var/www/TripSheetBackend
            git fetch --all
            git reset --hard origin/main
            git pull origin main
            npm install
            
            # Switch to deploy user and start PM2
            sudo -u deploy bash -c '
              cd /var/www/TripSheetBackend
              if pm2 list | grep -q "trip-sheet-backend"; then
                pm2 restart trip-sheet-backend
              else
                pm2 start app.js --name trip-sheet-backend
              fi
              pm2 save
            '
          EOF
